config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :categories
  resources :coordinators
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'course/home'
  get 'course/course_detail'
  get 'course/coordinator_detail'
  get 'course/course_of_category'
  get '/createlocation' , to:'locations#new'
  get '/createcategory' , to:'categories#new'
  get '/createcourse' , to:'courses#new'
  get  '/signup',  to: 'users#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'course#home'
  
  resources :locations do
    member do
      get :roll 
    end 
  end
 
  resources :courses do 
    member do 
      get  :locations
      post :location_add
      post :location_remove
      post 'vote'
      post 'down_vote'
    end 
  end
  
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to:user
    has_and_belongs_to_many:categories
    has_and_belongs_to_many:locations
    has_many :votes, dependent: :destroy
    has_many :voted_users, through: :votes, source: :user
    
    validates :name,  presence: true,length:{minimum:10}
    validates :prerequisite ,  presence: true,  length:{minimum:10}
    validates :description ,  presence: true,  length:{minimum:30}
    
    mount_uploader :image, ImageUploader
    
    
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def home
  end
  
  def course_detail
    if(params[:category_id] != nil)
      @category = Category.find_by_id(params[:category_id])
      @courses = @category.courses
    else if(params[:location_id] != nil)
      @location = Location.find_by_id(params[:location_id])
      @courses = @location.courses
    else
      @courses = Course.all
    end
    end
  end
  
  def coordinator_detail
    @users = User.all
  end
  
end

app/helpers/course_helper.rb
module CourseHelper
end

app/views/course/coordinator_detail.html.erb
<div class = "topDiv2">
    <h1>
        All coordinators
    </h1>
</div>

<div id="coursetable">
    <p> <%= link_to"Courses", course_course_detail_path%> | <%= link_to"Coordinators", course_coordinator_detail_path%>
</p> 

<hr>
 <% @users.each do |user| %>
 <div class="courserow">
 <div class = "coordinatordescriptiontext">
     <%= gravatar_for user %>
     <b>Coordinator name:</b><%= user.name %><br>
 </div>
 </div>
 <% end %>
 </div>

app/views/course/course_detail.html.erb
<div class = "topDiv2">
    <h1>
        <% if @location %>
        Location: <%= @location.name %>
        <% elsif @category %>
        Category: <%= @category.name %>
        <% else %>
        All Courses
        <%end %>
    </h1>
</div>
  
<div id="coursetable">
    <p> <%= link_to"Courses", course_course_detail_path%> | <%= link_to"Coordinators", course_coordinator_detail_path%>
</p> 

<hr>
    <%= render 'shared/course_table',object:@courses%>
</div>
  
  
  

</div>

app/views/course/home.html.erb
<% provide(:title, "Home") %>
<div class="topDiv">
<h1 id = "h1">
    Wlcome to your Course App
</h1>
<p>this is the home page for the RAD assignment 2</p>
    <%= link_to "<span class='glyphicon glyphicon-cog'></span>Sign up now!".html_safe, signup_path, class: "btn  btn-danger small" %>

</div>

<div id="row1">

<div id="column1">
<p class="t1">View Course as Guest User</p>
<p>Browse and view all courses as a guest and sign up later</p>
    <%= link_to "<span class='glyphicon glyphicon-book'></span>Browse all courses".html_safe, course_course_detail_path ,class:"btn btn-success small"%>
</div>

<div id="column2">
<p class="t1">Sign in to your account</p>
<p>Update your courses,rate courses,view coordinator informations</p>
    <%= link_to "<span class='glyphicon glyphicon-user'></span>Log in to your account".html_safe, login_path ,class:"btn btn-success small"%>
</div>

</div>