config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :categories
  resources :coordinators
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'course/home'
  get 'course/course_detail'
  get 'course/coordinator_detail'
  get 'course/course_of_category'
  get '/createlocation' , to:'locations#new'
  get '/createcategory' , to:'categories#new'
  get '/createcourse' , to:'courses#new'
  get  '/signup',  to: 'users#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'course#home'
  
  resources :locations do
    member do
      get :roll 
    end 
  end
 
  resources :courses do 
    member do 
      get  :locations
      post :location_add
      post :location_remove
      post 'vote'
      post 'down_vote'
    end 
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @locations = Location.all
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = current_user.courses.build(course_params)
    respond_to do |format|
      if @course.save
        flash[:success] = 'Course was successfully created' 
        format.html { redirect_to course_course_detail_path }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        flash[:success] = 'Course was successfully updated' 
        format.html { redirect_to course_course_detail_path }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, success: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
      # GET /courses/1/locations 
    def locations
      @course = Course.find(params[:id]) 
      @locations = @course.locations
    end      
    
    def categories
      @course = Course.find(params[:id])
      @categories = @course.categories
    end     
    
    
  def vote
    if (current_user!= nil)
      @course = Course.find(params[:id])
      @vote = @course.votes.create(user_id: current_user.id,kind:1)
      if @vote.save
        flash[:success] = "thanks for voting!"
      else
        flash[:danger] = "Error!You have already voted!"
      end
    else
      flash[:danger] = "you must login to vote"
    end
    redirect_to(course_course_detail_path)
  end
    
    def down_vote
     if (current_user!= nil)
      @course = Course.find(params[:id])
      @vote = @course.votes.create(user_id: current_user.id,kind:-1)
      if @vote.save
        flash[:success] = "thanks for voting!"
      else
        flash[:danger] = "Error!You have already voted!"
      end
     else
      flash[:danger] = "you must login to vote"
     end
    redirect_to(course_course_detail_path)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :prerequisite,:description,:image,:user_id,category_ids:[],location_ids:[])
    end
    
    
    
    
    

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :course_name %>
  </div>

  <div class="field">
    <%= form.label :prerequisite %>
    <%= form.text_field :prerequisite, id: :course_prerequisite %>
  </div>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :course_description,size:200 %>
  </div>  

  <div class="field">
    <%= form.label :category_id %>
    <div class = "checkbox-inline">
    <%= collection_check_boxes(:course,:category_ids, Category.all, :id, :name,item_wrapper_class: 'custom-control custom-control-inline') %>
    </div>
  </div>
  
  <div class="field form-group">
    <%= form.label :location_id %>
    <div class = "checkbox-inline">
    <%= collection_check_boxes(:course,:location_ids, Location.all, :id, :name,item_wrapper_class: 'custom-control custom-control-inline') %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prerequisite</th>
      <th>Coordinator</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.prerequisite %></td>
        <td><%= course.user_id %></td>
        <td><%= course.category_id %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p> 
<strong> Locations: </strong > 
  <% if !@course.locations.empty? %> 
    <%= @course.locations.collect{|l| link_to( l.name, l)}.join(",").html_safe%> 
  <% else %> 
      No locations added yet.
  <% end %>
</p> 

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Prerequisite:</strong>
  <%= @course.prerequisite %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @course.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @course.category_id %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to'Locations', locations_course_path(@course) %> |
<%= link_to 'Back', courses_path %>