config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :categories
  resources :coordinators
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'course/home'
  get 'course/course_detail'
  get 'course/coordinator_detail'
  get 'course/course_of_category'
  get '/createlocation' , to:'locations#new'
  get '/createcategory' , to:'categories#new'
  get '/createcourse' , to:'courses#new'
  get  '/signup',  to: 'users#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'course#home'
  
  resources :locations do
    member do
      get :roll 
    end 
  end
 
  resources :courses do 
    member do 
      get  :locations
      post :location_add
      post :location_remove
      post 'vote'
      post 'down_vote'
    end 
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small footer-secondary">
   <div class="container">
    <div class="row text-left">
				<div class="col-sm-3">
				  <h5>Contact us</h5>
				  	<form action="webmaster@rmit.com" method="post" enctype="text/plain">
						Name:<br>
						<input type="text" name="name"><br>
						E-mail:<br>
						<input type="text" name="mail"><br>
						Message:<br>
						<input type="text" name="message"><br>
						<input type="submit" value="Send">
					</form>
					
					<ul class="list-unstyled">
						<li>Telephone:0123456789</li>
						<li>Fax:012345678</li>
						<li>example@rmit.com</li>
					</ul>
				</div>
				<div class="col-sm-3">
					<h5>General Inquires</h5>
					<ul class="list-unstyled">
						<li>Andy Song</li>
						<li>Junliang Jiang</li>
						<li>Ail</li>
					</ul>
				</div>
				<div class="col-sm-3">
					<h5>Useful Links</h5>
					<ul class="list-unstyled">
						<li><a href="https://www.rmit.edu.au/study-with-us?gclid=EAIaIQobChMIjLCp8rX84QIVQoWPCh29kA8gEAAYASAAEgLlUvD_BwE&gclsrc=aw.ds">RMIT Course</a></li>
            <li><a href="https://www.rmit.edu.au/students/support-and-facilities/it-services-for-students/service-and-support-centre">RMIT Help Desk</a></li>
            <li><a href="https://www.rmit.edu.au/about/our-locations-and-facilities/locations/overseas">RMIT International</a></li>
					</ul>
				</div>
				<div class="col-sm-3">
					<h5>Media</h5>
					<ul class="list-unstyled">
					  
					  <!-- Icons made by Freepik from https://www.flaticon.com/ is licensed by Creative Commons BY 3.0 -->
					  
						<li><a href="https://www.youtube.com/" class="link"><span class="icon"><%= image_tag "icons/youtube.png" %></span>Youtube</a></li>
						<li><a href="https://www.facebook.com" class="link"><span class="icon"><%= image_tag "icons/facebook.png" %></span>Facebook</a></li>
						<li><a href="https://www.twitter.com" class="link"><span class="icon"><%= image_tag "icons/twitter.png" %></span>Twitter</a></li>
						<li><a href="https://www.skype.com" class="link"><span class="icon"><%= image_tag "icons/skype.png" %></span>Skype</a></li>
					</ul>
				</div>
				
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>

  
  <body>
      <nav class="navbar navbar-fixed-top navbar-default">
      <div class="container">
          <% if logged_in? %>
          <%= link_to "COURSE" ,course_course_detail_path,class:"navbar-left btn btn-info" %>
          <% else %>
          <%= link_to "COURSE" ,course_home_url,class:"navbar-left btn btn-info" %>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
          <li>
            <div class="dropdown">
                <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-record"></span>Category<span class="caret"></span></button>
                 <ul class="dropdown-menu">
                    <% @categories.each do |category| %>
                    <li><a><%= link_to category.name ,course_course_detail_path(:category_id => category.id) %></a></li>
                    <% end %>
                    <% if logged_in? %>
                    <li class="divider"></li>
                    <li><a><%= link_to 'create category' ,createcategory_path %></a></li>
                    <% end %>
                 </ul>
            </div>
          </li>
          <li>
            <div class="dropdown">
                 <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-map-marker"></span>Location<span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <% @locations.each do |location| %>
                    <li><a><%= link_to location.name ,course_course_detail_path(:location_id => location.id) %></a></li>
                    <% end %>
                    <% if logged_in? %>
                    <li class="divider"></li>
                    <li><a><%= link_to 'create location' ,createlocation_path %></a></li>
                    <% end %>
                   </ul>
            </div>
          </li>
          <% if logged_in? %>
          <li>
            <div class="dropdown">
            <%= link_to "NEW COURSE" ,createcourse_path,class:"btn btn-info" %>
            </div>
          </li>
          <% end %>
          <li>
            <div class="dropdown">
          <% if logged_in? %>
            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">
              Account <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><a><%= link_to "Profile", current_user %></a></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <a><%= link_to "Log out", logout_path, method: :delete %></a>
              </li>
            </ul>
        <% else %>
            
           <%= link_to "<span class = 'glyphicon glyphicon-user'></span>Log in".html_safe, login_path ,class:"navbar-right btn btn-info"%>
        <% end %>
        </div>
           </li>
          </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  
  <%= render 'layouts/footer' %>
  
</html>